window.App = window.App || {};
App.gameMode = 'survie';
App.isDarkMode = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;

App.playerCharacter = null;
App.opponentCharacter = null;
App.currentWave = 1;

App.userData = getUserData();

// --- API SYNC ---
App.syncCombatStart = async function() {
    const connection = JSON.parse(localStorage.getItem('connection'));
    if (!connection || !connection.userid) return loadPage('connection');
    
    const user = firebase.auth().currentUser;
    const token = user ? await user.getIdToken() : '';

    const recaptchaToken = await App.getRecaptchaToken('combat_survie_start');
    const response = await fetch('/api/combat/start', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
            userId: user.uid,
            gameMode: 'survie',
            playerCharacter: App.playerCharacter,
            opponentCharacter: null, // Opponent generated by server
            recaptchaToken: recaptchaToken
        })
    });
    const data = await response.json();
    if (data.success) {
        // Synchronisation complète de l'état (joueur + adversaire + vague)
        App.playerCharacter = data.gameState.player;
        App.opponentCharacter = data.gameState.opponent;
        App.currentWave = data.gameState.wave || 1;
        
        // Si on reprend une partie qui était en attente d'upgrade
        if (data.gameState.waitingForUpgrade) {
            App.showUpgradeOptions();
        }

        App.updateUI();
        App.updateSpecialButton();
    }
};

App.executeServerAction = async function(action, extra = {}) {
    const buttons = ['attack-button', 'special-button', 'defense-button', 'items-button'];
    buttons.forEach(id => { const b = document.getElementById(id); if(b) b.disabled = true; });

    const connection = JSON.parse(localStorage.getItem('connection'));
    const user = firebase.auth().currentUser;
    const token = user ? await user.getIdToken() : '';

    const response = await fetch('/api/combat/action', {
        method: 'POST',
        headers: { 
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({ userId: connection.userid, action, ...extra })
    });

    const data = await response.json();
    if (data.success) {
        const results = data.results;
        
        if (results.logs) {
            for (const log of results.logs) {
                App.addCombatLog(log.text, log.color, log.side);
                if (!log.text.startsWith('Tour')) await new Promise(r => setTimeout(r, 600));
            }
        }

        App.playerCharacter = data.game.player;
        App.opponentCharacter = data.game.opponent;
        App.currentWave = data.game.wave;
        
        App.updateUI();
        App.updateSpecialButton();

        if (results.waveCleared) {
            App.showUpgradeOptions();
        } else if (results.gameOver) {
            if (data.results.updatedUserData) {
                localStorage.setItem('userData', JSON.stringify(data.results.updatedUserData));
            }
            if (data.results.masteryGameResult) {
                sessionStorage.setItem('masteryGameResult', JSON.stringify(data.results.masteryGameResult));
            }
            App.handleSurvivalRewards(App.currentWave);
        } else {
            buttons.forEach(id => { const b = document.getElementById(id); if(b) b.disabled = false; });
        }
    }
};

App.handleSurvivalRewards = function(wave) {
  const userData = getUserData();
  const log = document.getElementById('combat-log');
  if (log) {
      log.innerHTML += `<p>Vous avez été vaincu à la vague ${wave}. Voici vos récompenses :</p>
                        <p>Argent gagné: ${userData.fin_argent || 0}</p>
                        <p>XP gagné: ${userData.fin_xp || 0}</p>`;
  }

  // --- NETTOYAGE SESSION ---
  sessionStorage.removeItem('playerCharacter');
  sessionStorage.removeItem('opponentCharacter');
  const cheatBtn = document.getElementById('cheat-btn-dev');
  if (cheatBtn) cheatBtn.remove();

  setTimeout(() => {
    loadPage('fin_partie_survie');
  }, 2000);
};

App.upgradeStat = async function(stat) {
    const connection = JSON.parse(localStorage.getItem('connection'));
    const user = firebase.auth().currentUser;
    const token = user ? await user.getIdToken() : '';

    const response = await fetch('/api/combat/survival/upgrade', {
        method: 'POST',
        headers: { 
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({ userId: connection.userid, stat })
    });

    const data = await response.json();
    if (data.success) {
        App.playerCharacter = data.game.player;
        App.opponentCharacter = data.game.opponent;
        App.currentWave = data.game.wave;
        
        const logColor = App.isDarkMode ? 'white' : 'black';
        App.addCombatLog(`${App.playerCharacter.name} a amélioré la stat ${stat}.`, logColor, "center");
        
        App.updateUI();
        App.hideUpgradeOptions();
        
        // Re-enable buttons for the new wave
        const buttons = ['attack-button', 'special-button', 'defense-button', 'items-button'];
        buttons.forEach(id => { const b = document.getElementById(id); if(b) b.disabled = false; });
    }
};

// --- REDEFINITION HANDLERS ---
App.handleAttack = () => App.executeServerAction('attack');
App.handlePlayerDefense = () => App.executeServerAction('defend');
App.useSpecialAbility = () => App.executeServerAction('special');
App.playerAttack = App.handleAttack;
App.handleDefense = App.handlePlayerDefense;

// --- UI LOGIC ---
App.showUpgradeOptions = function() {
  const div = document.getElementById('upgrade-options');
  const last = App.playerCharacter.last_upgrade;
  div.style.display = 'block';
  div.innerHTML = '<h3>Choisissez une amélioration</h3>';

  ['pv', 'attaque', 'defense'].forEach(stat => {
    if (last === stat) return;
    const btn = document.createElement('button');
    btn.textContent = stat === 'pv' ? 'Augmenter PV' : stat === 'attaque' ? 'Augmenter Attaque' : 'Augmenter Défense';
    btn.onclick = () => App.upgradeStat(stat);
    div.appendChild(btn);
  });
};

App.hideUpgradeOptions = function() {
  document.getElementById('upgrade-options').style.display = 'none';
};

// --- INITIALIZATION ---
{
    const storedPlayer = sessionStorage.getItem('playerCharacter');
    if (storedPlayer) {
        App.playerCharacter = JSON.parse(storedPlayer);
        App.initializeCharacterProperties(App.playerCharacter, true);
        App.playerCharacter.last_upgrade = "null";
        
        // Pour la survie, l'adversaire est généré par le serveur au start
        App.syncCombatStart();
    } else {
        loadPage('index');
    }
}

if (App.playerCharacter && App.playerCharacter.name === "Boompy") {
  const specBtn = document.getElementById('special-button');
  if(specBtn) specBtn.style.display = 'none';
}

// --- INJECTION BOUTON DE TRICHE (DEV) ---
(function injectCheatButton() {
    if (document.getElementById('cheat-btn-dev')) return;
    const btn = document.createElement('button');
    btn.id = 'cheat-btn-dev';
    btn.innerText = 'TERMINER PARTIE (DEV)';
    btn.style.cssText = 'position:fixed; top:10px; right:10px; z-index:999999; background:red; color:white; border:2px solid white; border-radius:10px; padding:12px; font-weight:bold; cursor:pointer; box-shadow: 0 0 15px rgba(0,0,0,0.5);';
    btn.onclick = () => App.executeServerAction('cheat_fail');
    document.body.appendChild(btn);
})();

document.body.addEventListener('click', function(e) {
  if (e.target.closest('#toggle-stats')) App.toggleStatsPanel();
});

App.initStatsPanelState();
App.updateUI();
App.updateSpecialButton();